### ISSUE TITLE
질문이 있습니다 스장님

### ISSUE THREAD

**Issue by sulmoJ** [AUSG/coding-test-study-seanson2#1]
혹시 스터디 비참여자도 스터디 당일에 구경만 해도 되나요? 👀 👀 👀

**Comment by plzprayme** [comment]
별로 상관 없어 보이는데 ..
그래도 스터디원들에게 의견을 한번 물어보겠습니당~

**Comment by Ohyaelim** [comment]
@JeoungSulMo 엇 저는 완전반대합니다~🙅‍♀️

**Comment by plzprayme** [comment]
일단은 보류하겠습니다
